version: '3'
services:
  proy1:
    build:
      context: .
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - type: bind
        source: .
        target: "/home/proy1/src"
    entrypoint: /run_jupyter.sh
    