version: '3'

services:

  fastapi:
    image : marinho14/inference_image:tag
    ports:
      - "8083:8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Limitar el contenedor a utilizar el 50% de una CPU
          memory: 512M  # Limitar el contenedor a utilizar 512 MB de memoria
        reservations:
          memory: 256M  # Reservar 256 MB de memoria para el contenedor
          
  locustmaster:
    image: locustio/locust
    container_name: locustmaster
    build: .
    ports:
     - "8082:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://locustmaster:8089
  
  locustworker:
    image: locustio/locust
    container_name: locustworker
    build: .
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locustmaster

  